<?php

namespace App\Filament\Resources\PostResource\Pages;

use App\Events\Post\CreatedEvent;
use App\Filament\Resources\PostResource;
use App\Models\Post;
use Filament\Resources\Pages\CreateRecord;

/**
 * @property Post $record
 */
class CreatePost extends CreateRecord
{
    protected static string $resource = PostResource::class;

    //    public function create(bool $another = false): void {
    //        return parent::create($another); // TODO: Change the autogenerated stub
    //    }

    protected function afterCreate(): void
    {
        CreatedEvent::dispatch($this->record);
    }
}
